- hosts: rpis
  tasks:
  - name: Set authorized key took from url
    authorized_key:
      user: pi
      state: present
      key: https://raw.githubusercontent.com/rakhbari/rpi-provision/master/rpi_authorized_keys.txt
