- hosts: all
  remote_user: pi
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - ../config/vars.yaml
  tasks:
  - name: Ensure rsyslog remote-server.conf
    template:
      src: ../config/rsyslog/remote-server.conf.j2
      dest: /etc/rsyslog.d/remote-server.conf
    tags: syslog
  - name: Ensure rsyslog queue-events.conf
    copy:
      src: ../config/rsyslog/queue-events.conf
      dest: /etc/rsyslog.d/queue-events.conf
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"
    tags: syslog
